# Do not edit. Generated by the configure script.
export PATH:=/Users/ramy/Development/projects/Module 3 Project/node/out/tools/bin:$(PATH)
PYTHON=/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
BUILDTYPE=Release
USE_XCODE=0
NODE_TARGET_TYPE=
PREFIX=/usr/local
